### ISSUE TITLE
Best way to prefetch images

### ISSUE THREAD

**Issue by fcisio** [cloudinary/js-url-gen#425]
Hi, I have a slider component that renders a single image at a time.
This means that each image is fetched as it should be displayed/visible.

I want to prefetch the next 2 images, but I don't know what the best way to approach this is.

> I'm using the SDK V2 (with react), along with the `responsive(plugin)`, so I would need to preserve the plugin behavior while prefetching.

Thanks

**Comment by patrick-tolosa** [comment]
Hey @fcisio - That's a very interesting use case. 

The issue with `responsive()` is that it calculates the size of the image based on the container, which means that only when the image is placed on the DOM we know the actual size, and thus know the final URL of the image (which includes the correct resizing).

The possible solutions here depend on your implementation:
Are you rendering all the slides, and then navigating between them, or are you generating each slide on demand when the user navigates to the next slide?

This is in fact not a cloudinary-specific question, as you'd face the same problem for any dynamically calculated URL.

I think you have a few options here, depending on your needs of course:
1. Do not use the `responsive()` plugin, slides can usually be created with a fixed width which you can set using the `image.resize(scale())` functions
2. Use `responsive()`, but also include a `placeholder()` plugin which will load a low-quality image first, and then will load the full image - this of course depends on the size of the images, and your specific needs.
3.  Render the slides in pairs of two, instead of one by one (assuming you're doing that), causing the next slide to always be ready for display.
4. Some frontend magic - in the same slide where you're rendering your image, render the next image in a hidden CSS element (Similar to the "two slide rendering solution".

As mentioned above, these are just generic front-end suggestions, and some of them are not directly related to Cloudinary.
Please let me know if you have additional quesitons.

**Comment by fcisio** [comment]
Hey @patrick-tolosa , thanks for your input!

I ended up rendering the slides in pairs (while hiding the next one with CSS). Not the cleanest solution, but it's worth it to preserve the responsive behavior.

**Comment by patrick-tolosa** [comment]
I'm glad to hear you found a working solution for your use case :)
