### ISSUE TITLE
Setting URLConfig.signUrl doesn't actually sign the URL

### ISSUE THREAD

**Issue by jonasb** [cloudinary/js-url-gen#451]
From what I can see setting signUrl on URL config doesn't have any effect. It seems like I need calculate the signature myself.

Am I missing something?

**Comment by patrick-tolosa** [comment]
@jonasb as mentioned, this SDK is currently client-side only, we plan to add some server-side functionality (such as URL signatures) in the near future.

I'm closing this issue for now, but please reply if needed.

**Comment by mikestopcontinues** [comment]
Hey, what's the status on adding signing?

**Comment by mikestopcontinues** [comment]
Just to follow up: The library makes it more difficult than normal to sign the request because it conceals the transformations that would otherwise need to be sorted, serialized, and signed. It would be great to have something like:

```ts
image.setSignature((payload) => string);
```

Or perhaps even:

```ts
new Cloudinary().setHasher((string) => string);
```

In the latter case, the library could manage which URLs needed to be signed (either by config or by `.sign()`)... which I suspect is what most users would expect. Thoughts?

**Comment by PixelCook** [comment]
@mikestopcontinues thanks for the feedback, this fix is currently still slotted for development. I don't currently have an ETA but I'll double-check with the team for an update.

**Comment by mikestopcontinues** [comment]
@PixelCook Any update on the ETA?

**Comment by PixelCook** [comment]
@mikestopcontinues Currently I do not have a date yet, but it is still slotted for development.
